name: Delete PR Environemnt

on:
  pull_request:
    types: [closed]

jobs:
  delete-app:
    name: Remove DigitalOcean App
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Delete App
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          doctl apps list --no-header --format ID,Spec.Name \
             | grep identity-pr-${PR_NUM} \
             | cut -b1-36 \
             | tee app.id
          doctl apps delete -f $(cat app.id)

