name: Delete PR Environemnt

on:
  pull_request:
    types: [closed]

jobs:
  delete-app:
    name: Remove DigitalOcean App
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        shell: bash 
        run: |
          echo ${GITHUB_HEAD_REF#refs/heads/} \
             | tee head.ref
          echo "::set-output name=branch::$(cat head.ref)"
        id: extract

      - name: Transform Branch Name
        shell: bash
        env:
          BRANCH_NAME: ${{ steps.extract.outputs.branch }}
        run: |
          echo $BRANCH_NAME \
             | tr '_./' '-' \
             | tr -Cd '[:alnum:]-\n' \
             | tee branch.name
          echo "::set-output name=app_name::$(cat branch.name)"
        id: tr

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Delete App
        env:
          APP_NAME: ${{ steps.tr.outputs.app_name }}
        run: |
          doctl apps list --no-header --format ID,Spec.Name \
             | grep pr-$APP_NAME \
             | cut -b1-36 \
             | tee app.id
          doctl apps delete -f $(cat app.id)

